function Hd = firFilter
%GETFILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.1 and DSP System Toolbox 24.1.
% Generated on: 17-Nov-2024 23:01:52

Fstop = 2;     % Stopband Frequency
Fpass = 5;     % Passband Frequency
Astop = 60;    % Stopband Attenuation (dB)
Apass = 1;     % Passband Ripple (dB)
Fs    = 1000;  % Sampling Frequency

h = fdesign.highpass('fst,fp,ast,ap', Fstop, Fpass, Astop, Apass, Fs);

Hd = design(h, 'equiripple', ...
    'MinOrder', 'any', ...
    'StopbandShape', 'flat');
end
