function Hd = design_filter
%GETFILTER Returns a discrete-time filter System object.

% MATLAB Code
% Generated by MATLAB(R) 24.1 and DSP System Toolbox 24.1.
% Generated on: 25-Mar-2025 19:15:14

N    = 2;      % Order
F3dB = 20;     % 3-dB Frequency
Fs   = 48000;  % Sampling Frequency

h = fdesign.lowpass('n,f3db', N, F3dB, Fs);

Hd = design(h, 'butter', ...
    'SystemObject', true,...
    UseLegacyBiquadFilter=true);

% save
save('filter_object.mat', 'Hd');
disp('Фильтр спроектирован и сохранен в файл filter_object.mat');